/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsOrgnodetypesRouteImport } from './routes/settings/orgnodetypes'
import { Route as SettingsCountriesRouteImport } from './routes/settings/countries'
import { Route as SettingsCitiesRouteImport } from './routes/settings/cities'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOrgnodetypesRoute = SettingsOrgnodetypesRouteImport.update({
  id: '/orgnodetypes',
  path: '/orgnodetypes',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCountriesRoute = SettingsCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCitiesRoute = SettingsCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/cities': typeof SettingsCitiesRoute
  '/settings/countries': typeof SettingsCountriesRoute
  '/settings/orgnodetypes': typeof SettingsOrgnodetypesRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/settings/cities': typeof SettingsCitiesRoute
  '/settings/countries': typeof SettingsCountriesRoute
  '/settings/orgnodetypes': typeof SettingsOrgnodetypesRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/cities': typeof SettingsCitiesRoute
  '/settings/countries': typeof SettingsCountriesRoute
  '/settings/orgnodetypes': typeof SettingsOrgnodetypesRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employees'
    | '/settings'
    | '/settings/cities'
    | '/settings/countries'
    | '/settings/orgnodetypes'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employees'
    | '/settings/cities'
    | '/settings/countries'
    | '/settings/orgnodetypes'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/employees'
    | '/settings'
    | '/settings/cities'
    | '/settings/countries'
    | '/settings/orgnodetypes'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeesRoute: typeof EmployeesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/orgnodetypes': {
      id: '/settings/orgnodetypes'
      path: '/orgnodetypes'
      fullPath: '/settings/orgnodetypes'
      preLoaderRoute: typeof SettingsOrgnodetypesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/countries': {
      id: '/settings/countries'
      path: '/countries'
      fullPath: '/settings/countries'
      preLoaderRoute: typeof SettingsCountriesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/cities': {
      id: '/settings/cities'
      path: '/cities'
      fullPath: '/settings/cities'
      preLoaderRoute: typeof SettingsCitiesRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsCitiesRoute: typeof SettingsCitiesRoute
  SettingsCountriesRoute: typeof SettingsCountriesRoute
  SettingsOrgnodetypesRoute: typeof SettingsOrgnodetypesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCitiesRoute: SettingsCitiesRoute,
  SettingsCountriesRoute: SettingsCountriesRoute,
  SettingsOrgnodetypesRoute: SettingsOrgnodetypesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeesRoute: EmployeesRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
